language: php

php:
  - "7.2"

git:
  depth: 1

services:
  - docker

branches:
  only:
    - master

addons:
  apt:
    update: true

before_install:
  export PATH=$PATH:/home/travis/.config/composer/vendor/bin

install:
  - sudo apt install realpath
  - composer global require wi1dcard/learnku-deploy-bot:dev-master

before_script:
  - helpers/lint

script:
  - helpers/deploy

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
